name: LumaItems
version: '${version}'
main: dev.jsinco.luma.lumaitems.LumaItems
api-version: '1.21'
author: 'Jsinco'
#libraries: ['org.jetbrains.kotlin:kotlin-stdlib:2.0.21']
depend:
  - LumaCore
softdepend:
- PlaceHolderAPI
- EvenMoreFish # Softdepending EMF to register listeners after it
- ProtocolLib
- MythicMobs
- Jobs
permissions:
  lumaitems.disassemblergui:
    description: Permission to open the disassembler GUI
    default: op