name: LumaItems
version: '${version}'
main: dev.lumas.lumaitems.LumaItems
api-version: '1.21'
author: 'Jsinco'
folia-supported: true
depend:
  - LumaCore
softdepend:
  - ProtocolLib
  - EvenMoreFish # Softdepending EMF to register listeners after it
  - Jobs
  - mcMMO
permissions:
  lumaitems.disassemblergui:
    description: Permission to open the disassembler GUI
    default: op
