package dev.lumas.lumaitems.configuration.files

import dev.lumas.lumaitems.annotations.File
import dev.lumas.lumaitems.configuration.OkaeriFile
import eu.okaeri.configs.OkaeriConfig
import eu.okaeri.configs.annotation.CustomKey
import org.bukkit.Bukkit
import org.bukkit.Location
import org.bukkit.Material

@File("relics.yml")
class RelicsYml : OkaeriFile() {

    var disassembler = DisassemblerSection()
    @CustomKey("relic-materials")
    var relicMaterials = RelicMaterialsSection()
    var names = NamesSection()

    class DisassemblerSection : OkaeriConfig() {
        var commands: Map<Int, String> = mapOf(
            5 to "lumaitems relic %player% core lunar",
            20 to "csap box rare %player%",
            29 to "points give %player% 5",
            39 to "repairtoken give %player% Repair3 1",
            41 to "csap box common %player%",
            60 to "give %player% experience_bottle 16",
            38 to "give %player% netherite_scrap 1",
            45 to "repairtoken give %player% Repair2 1",
            42 to "give %player% diamond 3",
            48 to "give %player% iron_ingot 5",
            47 to "repairtoken give %player% Repair1 1",
            43 to "give %player% gold_ingot 5",
            50 to "give %player% coal_block 4",
            44 to "lumaitems relic %player% shard 4"
        )

        var blocks: Map<String, Location> = mapOf(
            "spawnDec" to Location(Bukkit.getWorld("spawn"), 199.0, 61.0, 215.0)
        )
    }

    class RelicMaterialsSection : OkaeriConfig() {
        var lunar: List<Material> = listOf(
            Material.DIAMOND_HELMET,
            Material.DIAMOND_CHESTPLATE,
            Material.DIAMOND_LEGGINGS,
            Material.DIAMOND_BOOTS,
            Material.DIAMOND_SWORD,
            Material.DIAMOND_PICKAXE,
            Material.DIAMOND_AXE,
            Material.DIAMOND_SHOVEL,
            Material.DIAMOND_HOE
        )

        var nova: List<Material> = listOf(
            Material.COPPER_HELMET,
            Material.COPPER_CHESTPLATE,
            Material.COPPER_LEGGINGS,
            Material.COPPER_BOOTS,
            Material.COPPER_SWORD,
            Material.COPPER_PICKAXE,
            Material.COPPER_AXE,
            Material.COPPER_SHOVEL,
            Material.COPPER_HOE,
            Material.GOLDEN_HELMET,
            Material.GOLDEN_CHESTPLATE,
            Material.GOLDEN_LEGGINGS,
            Material.GOLDEN_BOOTS,
            Material.GOLDEN_SWORD,
            Material.GOLDEN_PICKAXE,
            Material.GOLDEN_AXE,
            Material.GOLDEN_SHOVEL,
            Material.GOLDEN_HOE,
            Material.IRON_SWORD,
            Material.IRON_PICKAXE,
            Material.IRON_AXE,
            Material.IRON_SHOVEL,
            Material.IRON_HOE,
            Material.CHAINMAIL_HELMET,
            Material.CHAINMAIL_CHESTPLATE,
            Material.CHAINMAIL_LEGGINGS,
            Material.CHAINMAIL_BOOTS,
            Material.LEATHER_HELMET,
            Material.LEATHER_CHESTPLATE,
            Material.LEATHER_LEGGINGS,
            Material.LEATHER_BOOTS,
            Material.STONE_SWORD,
            Material.STONE_PICKAXE,
            Material.STONE_AXE,
            Material.STONE_SHOVEL,
            Material.STONE_HOE,
            Material.BOW
        )

        var pulsar: List<Material> = listOf(
            Material.COPPER_HELMET,
            Material.COPPER_CHESTPLATE,
            Material.COPPER_LEGGINGS,
            Material.COPPER_BOOTS,
            Material.COPPER_SWORD,
            Material.COPPER_PICKAXE,
            Material.COPPER_AXE,
            Material.COPPER_SHOVEL,
            Material.COPPER_HOE,
            Material.GOLDEN_HELMET,
            Material.GOLDEN_CHESTPLATE,
            Material.GOLDEN_LEGGINGS,
            Material.GOLDEN_BOOTS,
            Material.GOLDEN_SWORD,
            Material.GOLDEN_PICKAXE,
            Material.GOLDEN_AXE,
            Material.GOLDEN_SHOVEL,
            Material.GOLDEN_HOE,
            Material.IRON_SWORD,
            Material.IRON_PICKAXE,
            Material.IRON_AXE,
            Material.IRON_SHOVEL,
            Material.IRON_HOE,
            Material.CHAINMAIL_HELMET,
            Material.CHAINMAIL_CHESTPLATE,
            Material.CHAINMAIL_LEGGINGS,
            Material.CHAINMAIL_BOOTS,
            Material.LEATHER_HELMET,
            Material.LEATHER_CHESTPLATE,
            Material.LEATHER_LEGGINGS,
            Material.LEATHER_BOOTS,
            Material.STONE_SWORD,
            Material.STONE_PICKAXE,
            Material.STONE_AXE,
            Material.STONE_HOE,
            Material.WOODEN_PICKAXE,
            Material.WOODEN_AXE,
            Material.WOODEN_SHOVEL,
            Material.BOW
        )

        var solar: List<Material> = listOf(
            Material.CHAINMAIL_HELMET,
            Material.CHAINMAIL_CHESTPLATE,
            Material.CHAINMAIL_LEGGINGS,
            Material.CHAINMAIL_BOOTS,
            Material.LEATHER_HELMET,
            Material.LEATHER_CHESTPLATE,
            Material.LEATHER_LEGGINGS,
            Material.LEATHER_BOOTS,
            Material.STONE_SWORD,
            Material.STONE_PICKAXE,
            Material.STONE_AXE,
            Material.STONE_SHOVEL,
            Material.STONE_HOE,
            Material.WOODEN_PICKAXE,
            Material.WOODEN_AXE,
            Material.WOODEN_SHOVEL,
            Material.WOODEN_HOE,
            Material.BOW
        )

        var delta: List<Material> = listOf(
            Material.WOODEN_SPEAR,
            Material.STONE_SPEAR,
            Material.COPPER_SPEAR,
            Material.LEATHER,
            Material.CROSSBOW,
            Material.CHAINMAIL_HELMET,
            Material.CHAINMAIL_CHESTPLATE,
            Material.CHAINMAIL_LEGGINGS,
            Material.CHAINMAIL_BOOTS,
            Material.LEATHER_HELMET,
            Material.LEATHER_CHESTPLATE,
            Material.LEATHER_LEGGINGS,
            Material.LEATHER_BOOTS,
            Material.STONE_SWORD,
            Material.STONE_PICKAXE,
            Material.STONE_AXE,
            Material.STONE_SHOVEL,
            Material.STONE_HOE,
            Material.WOODEN_PICKAXE,
            Material.WOODEN_AXE,
            Material.WOODEN_SHOVEL,
            Material.WOODEN_HOE
        )
    }


    class NamesSection : OkaeriConfig() {
        var prefixes: List<String> = listOf(
            "Bleak",
            "Spotlight",
            "Liar's",
            "Soul",
            "Apple Slice",
            "Imagination",
            "Candy",
            "White Wool",
            "Lover's",
            "Telephone",
            "City Pop",
            "Ice Cube",
            "Yam",
            "Circus",
            "Carnival",
            "Phoenix",
            "Reflections",
            "Opera House",
            "Clouded Skies",
            "Zodiac",
            "Blonde",
            "Cotton Candy",
            "Sweet Soul",
            "Egyptian",
            "Utopian",
            "Sakura",
            "Cherry",
            "Oak",
            "Crew",
            "Crimson",
            "Forgotten",
            "Boss'",
            "Green Thumb",
            "Trooper",
            "Smash",
            "Nameless",
            "Soda",
            "Beluga",
            "J's",
            "Witch's",
            "Rats'",
            "Saiyan's",
            "Sugar Apple",
            "Lightwater",
            "Plastic",
            "Lasting",
            "Deni's",
            "Kujo's",
            "Kat's",
            "Unreal",
            "Didi's",
            "Rat",
            "Psycho",
            "Dim's",
            "Bayleaf's",
            "Limz's",
            "Kek's",
            "Mystic",
            "King's",
            "Queen's",
            "Pauper",
            "PC's",
            "Bjorn's",
            "WitchBiscuit's",
            "Nerdy",
            "Potato",
            "Winlo's",
            "Drew's",
            "Cobra",
            "Magician's",
            "Last",
            "Nebula",
            "Tidal Wave",
            "Beach House",
            "Saxaphone",
            "Angelic",
            "Friction",
            "Party",
            "Bounce House",
            "Fruitful",
            "Note",
            "Fantasy Dream",
            "Fantasia",
            "Rojo",
            "Diamond",
            "Shadow",
            "Material",
            "Greek",
            "Flagged",
            "Luma",
            "Luna",
            "Jaunty",
            "Janty",
            "Lumin",
            "Mayor's",
            "Peasant",
            "Snowy",
            "Car",
            "Breathing",
            "Hot Air",
            "Cold Sweat",
            "Smiling",
            "Happy Day",
            "Cherry",
            "Blossom",
            "Lost",
            "Insanity",
            "Spotted",
            "Spooder",
            "Dotted",
            "Caught",
            "Soft Smile",
            "Osh's",
            "Lily's",
            "Rose",
            "Rock",
            "Ugly Sweater",
            "Tree",
            "Stinky",
            "Coffee's",
            "Krox's",
            "Prism's",
            "Bailey's",
            "Soda's",
            "Legit's",
            "Brand's",
            "Tom's",
            "Adora's",
            "Oddi's",
            "Bubbles'",
            "Leah's",
            "Tsui's",
            "Sunni's",
            "Slime's",
            "Casper's",
            "Autumn's",
            "Ara's",
            "Syielves'",
            "Maddie's",
            "Purple's",
            "Diverse's",
            "Bea's",
            "Tisol's",
            "Mlien's",
            "Duck's",
            "Corpes'",
            "Daisy's",
            "Lee's",
            "Saph's",
            "Fiellessi's",
            "Mush's",
            "Seiten's",
            "Max's",
            "yessir's",
            "McArth's",
            "Num's",
            "Wetketchup's"
        )

        var suffixes: List<String> = listOf(
            "Vortex",
            "Elegance",
            "Apex",
            "Serenity",
            "Panorama",
            "Silhouette",
            "Opulence",
            "Oracle",
            "Muse",
            "Mosaic",
            "Chalice",
            "Vestige",
            "Paragon",
            "Paradox",
            "Grace",
            "Tranquility",
            "Horizon",
            "Reverie",
            "Echo",
            "Enigma",
            "Anomaly",
            "Aberration",
            "Exception",
            "Unity",
            "Solitude",
            "Ascent",
            "Mirage",
            "Abyss",
            "Remnant",
            "Whisper",
            "Revenant",
            "Labyrinth",
            "Synchrony",
            "Nocturne",
            "Nemesis",
            "Crescendo",
            "Incense",
            "Resonance",
            "Serenade",
            "Calling",
            "Brewing",
            "Everlasting",
            "Nest",
            "Nexus",
            "Package",
            "Class",
            "Junction",
            "Methoding",
            "Drink",
            "Cheating",
            "Fastening",
            "Speed",
            "Longevity",
            "Vitality",
            "Heart",
            "Bently",
            "LightSaber",
            "Shinings",
            "Savings",
            "Forgetfulness",
            "Happiness",
            "Job",
            "Feelings",
            "Power",
            "Might",
            "Chance",
            "Lumin",
            "Smile",
            "Monster",
            "Eggs",
            "Spider",
            "Man",
            "Bunny",
            "Love",
            "Joker",
            "Hugs"
        )
    }
}
